name: Update README

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB\_TOKEN: ${{ secrets.GITHUB\_TOKEN }}
